# reload config file
bind r source-file ~/.tmux.conf

# Setting True Color
set -g default-terminal "tmux-256color"
set -sa terminal-features ",*:RGB"

# split panes using h and v
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# switch panes using Crtl-arrow without prefix
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D

# navigate windows using left home row
bind -n C-d select-window -t :0
bind -n C-h select-window -t :1
bind -n C-t select-window -t :2
bind -n C-n select-window -t :3
unbind 0
unbind 1
unbind 2
unbind 3

# Style the status bar
set -g status-position top
set -g status-justify centre
set -g status-left ''
set -g status-right ''

# center the windows
set -g window-status-format ' #W '
set -g window-status-current-format ' [#W] '

# invert color pallet
set -g status-style 'bg=default'
set -g window-status-style 'fg=green'
