#!/usr/bin/env bash
## Boiler plate
export SCRIPTPATH="$( cd "$(dirname "$0")"; pwd -P )"
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down
	rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

## Load wallpaper and compositor
wallpaper_path=~/.local/share/backgrounds/nocturnal_white_1080p.jpg
if [[ -x "$(command -v feh)" && -e "$wallpaper_path" ]]; then
	feh --no-fehbg --bg-scale "$wallpaper_path"

if [[ -x "$(command -v fastcompmgr)" ]]; then
	fastcompmgr -c -C -o 1.0 -i 0.7
fi
